// FIFA 3-letter code → demonym (the adjective form, lowercase) used in
// "FanRoute's {demonym}-fan bars" headers. Lowercase here; capitalize at
// the call site if needed.

const DEMONYMS: Record<string, string> = {
  USA: "American",
  MEX: "Mexican",
  CAN: "Canadian",
  ENG: "English",
  SCO: "Scottish",
  WAL: "Welsh",
  NIR: "Northern Irish",
  IRL: "Irish",
  FRA: "French",
  GER: "German",
  ESP: "Spanish",
  POR: "Portuguese",
  NED: "Dutch",
  BEL: "Belgian",
  ITA: "Italian",
  CRO: "Croatian",
  SUI: "Swiss",
  AUT: "Austrian",
  POL: "Polish",
  NOR: "Norwegian",
  DEN: "Danish",
  SWE: "Swedish",
  FIN: "Finnish",
  ISL: "Icelandic",
  TUR: "Turkish",
  GRE: "Greek",
  HUN: "Hungarian",
  CZE: "Czech",
  SVK: "Slovak",
  SVN: "Slovenian",
  ROU: "Romanian",
  BUL: "Bulgarian",
  SRB: "Serbian",
  UKR: "Ukrainian",
  ARG: "Argentine",
  BRA: "Brazilian",
  URU: "Uruguayan",
  COL: "Colombian",
  ECU: "Ecuadorian",
  PAR: "Paraguayan",
  CHI: "Chilean",
  PER: "Peruvian",
  VEN: "Venezuelan",
  BOL: "Bolivian",
  CRC: "Costa Rican",
  PAN: "Panamanian",
  JAM: "Jamaican",
  HON: "Honduran",
  HAI: "Haitian",
  MAR: "Moroccan",
  TUN: "Tunisian",
  EGY: "Egyptian",
  ALG: "Algerian",
  GHA: "Ghanaian",
  SEN: "Senegalese",
  CIV: "Ivorian",
  NGA: "Nigerian",
  CMR: "Cameroonian",
  RSA: "South African",
  CPV: "Cape Verdean",
  JPN: "Japanese",
  KOR: "South Korean",
  AUS: "Australian",
  IRN: "Iranian",
  IRQ: "Iraqi",
  KSA: "Saudi",
  QAT: "Qatari",
  UAE: "Emirati",
  UZB: "Uzbek",
  JOR: "Jordanian",
  CHN: "Chinese",
  IND: "Indian",
  THA: "Thai",
  VIE: "Vietnamese",
  IDN: "Indonesian",
  NZL: "New Zealand",
};

export function demonym(fifaCode: string): string | null {
  if (!fifaCode) return null;
  return DEMONYMS[fifaCode.toUpperCase()] ?? null;
}
